{
    "name": "Mail WhatsApp",
    "version": "18.0.1.36.0",
    "images": ["static/description/icon.png"],
    "category": "Discuss",
    "summary": "WhatsApp Cloud API with Meta Coexistence via Embedded Signup",
    "author": "andyengit",
    "maintainer": "andyengit",
    "website": "https://github.com/andyengit",
    "license": "LGPL-3",
    "depends": ["mail", "phone_validation", "base_setup"],
    "external_dependencies": {
        "python": ["phonenumbers", "requests"],
    },
    "data": [
        "security/mail_whatsapp_security.xml",
        "security/ir.model.access.csv",
        "data/res_partner_category_data.xml",
        "data/mail_activity_type_data.xml",
        "data/mail_activity_type_whatsapp_followup.xml",
        "data/ir_cron_data.xml",
        "wizards/mail_whatsapp_test_send_views.xml",
        "wizards/mail_whatsapp_test_receive_views.xml",
        "wizards/mail_whatsapp_composer_views.xml",
        "wizards/mail_whatsapp_followup_views.xml",
        "views/mail_whatsapp_account_views.xml",
        "views/mail_whatsapp_message_views.xml",
        "views/mail_whatsapp_template_views.xml",
        "views/mail_whatsapp_tag_views.xml",
        "views/mail_whatsapp_data_deletion_views.xml",
        "views/mail_whatsapp_dashboard_views.xml",
        "views/res_config_settings_views.xml",
        "views/mail_whatsapp_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "mail_whatsapp/static/src/core/common/**/*",
            "mail_whatsapp/static/src/core/web/**/*",
            "mail_whatsapp/static/src/core/public_web/**/*",
            "mail_whatsapp/static/src/discuss/**/*",
            "mail_whatsapp/static/src/chatter/**/*",
            "mail_whatsapp/static/src/embedded_signup/**/*",
            "mail_whatsapp/static/src/demo_receive/**/*",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
}
