# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    "name": "Powered By Andy - SaaS Enterprise",
    "icon": "/poweredbyandy_e_saas/static/description/icon.png",
    "summary": "Instala los módulos base del SaaS de Venezuela compatibles con Enterprise",
    "version": "18.0.1.0.2",
    "category": "Accounting/Localizations",
    "website": "https://github.com/OCA/l10n-venezuela",
    "author": "andyengit",
    "maintainers": ["andyengit"],
    "license": "AGPL-3",
    "application": True,
    "installable": True,
    "post_init_hook": "post_init_hook",
    "data": [
        "data/res_users.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "poweredbyandy_e_saas/static/src/xml/home_menu_watermark.xml",
            "poweredbyandy_e_saas/static/src/scss/home_menu_watermark.scss",
        ],
    },
    "depends": [
        "account",
        "account_accountant",
        "web_enterprise",
        "purchase",
        "stock",
        "delivery",
        "sale_management",
        "sale_margin",
        "l10n_ve_seniat",
        "l10n_ve_seniat_sale",
        "l10n_ve_stock",
        "l10n_ve_reports",
        "l10n_ve_igtf",
        "l10n_ve_withholding",
        "l10n_ve_exchange_rates",
        "l10n_ve_product_currency",
        "l10n_ve_sale_product_pricelist_catalog",
        "l10n_ve_audit",
        "currency_account",
        "currency_purchase",
        "currency_sale",
        "currency_rate_update",
        "res_currency_rate_provider_BCV",
        "l10n_ve_bank_statement_import",
        "web_chatter_position",
        "portal_odoo_debranding",
        "web_dialog_size",
        "web_datetime_picker_default_time",
        "web_excel_export_dynamic_expand",
        "web_search_with_and",
        "web_widget_numeric_step",
        "web_copy_confirm",
        "web_company_color",
        "web_group_expand",
        "partner_vat_unique",
        "account_invoice_refund_link",
        "account_invoice_supplierinfo_update",
        "account_statement_import_base",
        "account_statement_import_sheet_file",
        "developer_menu",
        "disable_odoo_online",
        "google_calendar",
        "microsoft_calendar",
        "partner_ref_unique",
        "product_margin",
        "partner_external_map",
        "partner_contact_birthdate",
        "partner_contact_age_range",
        "web_pwa_customize",
        "board",
    ],
}
