{
    "name": "Cash Box",
    "version": "18.0.1.0.0",
    "category": "Accounting/Accounting",
    "summary": "Systray cash box for daily in/out, closing and journal balances",
    "author": "andyengit",
    "maintainer": "andyengit",
    "website": "https://github.com/andyengit",
    "license": "LGPL-3",
    "images": ["static/description/icon.png"],
    "depends": ["account"],
    "data": [
        "security/account_cash_box_groups.xml",
        "security/ir.model.access.csv",
        "security/account_cash_box_security.xml",
        "data/ir_sequence_data.xml",
        "views/account_cash_box_views.xml",
        "views/account_cash_reason_views.xml",
        "views/account_cash_session_views.xml",
        "views/account_cash_move_views.xml",
        "views/account_journal_views.xml",
        "wizard/account_cash_open_views.xml",
        "wizard/account_cash_move_views.xml",
        "wizard/account_cash_close_views.xml",
        "views/account_cash_box_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "account_cash_box/static/src/systray/cash_box_systray.scss",
            "account_cash_box/static/src/systray/cash_box_dialogs.js",
            "account_cash_box/static/src/systray/cash_box_dialogs.xml",
            "account_cash_box/static/src/systray/cash_box_systray.js",
            "account_cash_box/static/src/systray/cash_box_systray.xml",
        ],
    },
    "installable": True,
    "application": True,
}
