from . import res_company
from . import res_config_settings
from . import res_partner
from . import product_pricelist_item
from . import pba_discount_policy
from . import sale_order
from . import sale_order_discount
from . import sale_order_line
from . import account_move_line
from . import account_daily_payments_report
