{
    "name": "PBA Discount Management",
    "version": "18.0.1.2.1",
    "summary": "Límites de descuento por compañía, contacto y permisos de descuento global",
    "category": "Sales",
    "author": "andyengit",
    "maintainer": "andyengit",
    "license": "LGPL-3",
    "depends": [
        "sale_management",
        "account",
        "l10n_ve_reports",
        "l10n_ve_seniat",
        "l10n_ve_seniat_sale",
    ],
    "data": [
        "security/pba_discount_management_groups.xml",
        "security/ir.model.access.csv",
        "data/daily_payments_report_column.xml",
        "views/res_config_settings_views.xml",
        "views/res_partner_views.xml",
        "views/sale_order_views.xml",
        "views/pba_hide_line_discount_views.xml",
        "wizard/account_move_discount_views.xml",
        "views/account_move_views.xml",
    ],
    "installable": True,
    "application": False,
}
