{
    "name": "PBA WhatsApp Contacto",
    "version": "18.0.1.0.20",
    "category": "Marketing",
    "summary": "Crea contactos automáticamente al recibir mensajes de WhatsApp",
    "author": "andyengit",
    "maintainer": "andyengit",
    "license": "LGPL-3",
    "depends": ["pba_whatsapp"],
    "auto_install": True,
    "data": [
        "security/ir.model.access.csv",
        "security/pba_whatsapp_template_send_security.xml",
        "security/pba_whatsapp_autoreply_security.xml",
        "views/pba_whatsapp_autoreply_rule_views.xml",
        "views/pba_whatsapp_autoreply_menus.xml",
        "views/mail_whatsapp_template_views.xml",
        "views/pba_whatsapp_template_send_wizard_views.xml",
        "views/mail_gateway_views.xml",
        "views/res_config_settings_views.xml",
    ],
    "installable": True,
    "application": False,
}
