from . import res_company
from . import res_config_settings
from . import pba_whatsapp_autoreply_rule
from . import pba_whatsapp_autoreply_config
from . import mail_gateway
from . import mail_gateway_whatsapp
from . import mail_whatsapp_mixin
from . import mail_whatsapp_template
from . import mail_whatsapp_template_variable
from . import mail_whatsapp_template_button
