{
    "name": "Website Auto Order Scanner",
    "version": "18.0.1.8.1",
    "category": "Website/Website",
    "summary": "Public OWL portal to scan barcodes or QR codes and buy with the website cart",
    "author": "andyengit",
    "maintainer": "andyengit",
    "website": "https://github.com/andyengit",
    "license": "LGPL-3",
    "depends": [
        "website_sale",
        "product_qrcode",
        "product_qrcode_portal",
    ],
    "data": [
        "data/website_menu.xml",
        "views/auto_order_templates.xml",
        "views/res_config_settings_views.xml",
        "views/website_views.xml",
    ],
    "assets": {
        "web_sale_auto_order.assets_kiosk": [
            ("include", "web.assets_frontend_minimal"),
            ("include", "web._assets_helpers"),
            "web/static/lib/luxon/luxon.js",
            "web/static/lib/owl/owl.js",
            "web/static/lib/owl/odoo_module.js",
            "web/static/src/legacy/js/core/class.js",
            "web/static/src/env.js",
            "web/static/src/core/utils/transitions.scss",
            "web/static/src/core/**/*",
            ("remove", "web/static/src/core/commands/**/*"),
            ("remove", "web/static/src/core/debug/debug_menu.js"),
            ("remove", "web/static/src/core/file_viewer/file_viewer.dark.scss"),
            ("remove", "web/static/src/core/emoji_picker/emoji_data.js"),
            "web/static/src/core/commands/default_providers.js",
            "web/static/src/core/commands/command_palette.js",
            "web/static/src/public/error_notifications.js",
            "web/static/src/public/public_component_service.js",
            "web/static/src/legacy/js/public/public_root.js",
            "web/static/src/legacy/js/public/public_root_instance.js",
            "web/static/src/legacy/js/public/public_widget.js",
            "web_sale_auto_order/static/src/auto_order.scss",
            "web_sale_auto_order/static/src/auto_order.js",
            "web_sale_auto_order/static/src/auto_order.xml",
        ],
        "web_sale_auto_order.zxing_assets": [
            "web/static/lib/zxing-library/zxing-library.js",
        ],
    },
    "installable": True,
    "application": False,
}
