{
    "name": "PBA Goal Commision",
    "version": "18.0.1.17.0",
    "post_init_hook": "post_init_hook",
    "summary": "Comisiones por metas de venta y cobro para vendedores",
    "author": "andyengit",
    "maintainer": "andyengit",
    "license": "LGPL-3",
    "category": "Accounting",
    "depends": ["account", "mail", "l10n_ve_reports", "currency_account"],
    "data": [
        "security/goal_commission_security.xml",
        "security/goal_commission_report_security.xml",
        "security/ir.model.access.csv",
        "views/res_config_settings_views.xml",
        "views/res_partner_views.xml",
        "views/account_move_views.xml",
        "views/goal_commission_billing_wizard_views.xml",
        "views/goal_commission_seller_views.xml",
        "views/goal_commission_menu_views.xml",
        "views/goal_commission_report_client_actions.xml",
        "report/ir_actions_report.xml",
        "report/goal_commission_report_templates.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "pba_goal_commision/static/src/goal_commission_reports/**/*.js",
            "pba_goal_commision/static/src/goal_commission_reports/**/*.xml",
            "pba_goal_commision/static/src/goal_commission_reports/**/*.scss",
        ],
    },
    "installable": True,
    "application": False,
}
