{
    "name": "PBA Alertas",
    "icon": "/pba_alerts/static/description/icon.png",
    "version": "18.0.1.0.3",
    "post_init_hook": "post_init_hook",
    "summary": "Actividades automáticas por sucesos de ventas, facturación e inventario",
    "category": "Productivity",
    "author": "andyengit",
    "maintainer": "andyengit",
    "license": "LGPL-3",
    "depends": [
        "mail",
        "account",
        "sale",
        "sale_stock",
        "stock",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron_data.xml",
        "data/pba_alert_data.xml",
        "data/pba_alert_created_invoice_data.xml",
        "data/pba_alert_sales_data.xml",
        "views/pba_alert_views.xml",
        "views/pba_alert_menu.xml",
    ],
    "installable": True,
    "application": False,
}
